// import { Inter } from "next/font/google";
import Theme from "@/components/Theme";
import "./globals.css";
import DarkLight from "@/components/DarkLight";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Theme>
          <DarkLight />{children}</Theme>
      </body>
    </html>
  );
}
